= Oracle JDBC Data Types Conversion

== Introduction

== Building from source
After you've downloaded the code from GitHub, you can build it using Gradle. Use this command:
---- 
gradle clean build
----
 
The generated jar files can be found at: `build/libs/`.

An uber jar containing the library and all its relocated dependencies except the Oracle JDBC driver can also be built. Use this command: 
----
gradle clean shadowJar
----

The generated uber jar file can also be found at: `build/libs/`. At runtime, the uber jar expects to find the Oracle JDBC driver on the classpath.
 
=== Validating secure dependencies
To ensure no security vulnerabilities in the dependency libraries, run the following.
----
gradle dependencyCheckAnalyze
----

If the above reports any vulnerabilities, upgrade dependencies to use the respective latest versions.

== Version and release history

=== 0.5.0 (SEP-2023)
Initial build


== Authors
**Aleksej Veremeev** - *Initial work* - http://a2-solutions.eu/[A2 Rešitve d.o.o.]

== License

This project is licensed under the Apache-2.0 License.

